### PUT Put Mapping 1
PUT http://localhost:8080/api/put-mapping

### PUT Rquest Mappping
PUT http://localhost:8080/api/request-mapping

### PUT Put Mapping 2
PUT http://localhost:8080/api/put-mapping/object
Content-Type: application/json

{
  "name": "steve",
  "age": 22,
  "email": "steve@gmail.com",
  "address": "경기도 성남시",
  "phone_number": "010-1234-1234"
}
