### Get Api
GET http://localhost:8080/api/hello

### Get PathVariable 1
GET http://localhost:8080/api/get-mapping/path-variable/steve

### Get PathVariable 2
GET http://localhost:8080/api/get-mapping/path-variable/steve/22

### Get PathVariable 3
GET http://localhost:8080/api/get-mapping/path-variable2/steve/22

### Get PathVariable 3
GET http://localhost:8080/api/get-mapping/query-param?name=steve&age=22
